module.exports = {
  apps: [
    {
      name: 'codelens-api',
      script: './apps/api/dist/index.js',
      cwd: '/root/CodeLens',
      instances: 1,
      exec_mode: 'fork',
      node_args: '--expose-gc --max-old-space-size=2560',
      env_production: {
        NODE_ENV: 'production',
        PORT: 8787,
        ANTHROPIC_BASE_URL: 'http://118.89.81.103:8081',
        ANTHROPIC_AUTH_TOKEN: 'sk-f2582742d1626781374d8476763c987b32e85fd8e8911c0ed2f7eff7e9413058',
        EMBED_API_KEY: 'sk-4002f08ebad741ea98a6978679f98328',
        EMBED_BASE_URL: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
        EMBED_MODEL: 'text-embedding-v3',
        EMBED_DIMENSIONS: '1024',
        DASHSCOPE_RERANK_MODEL: 'qwen3-rerank',
        DB_HOST: 'localhost',
        DB_PORT: '5432',
        DB_NAME: 'codelens',
        DB_USER: 'postgres',
        DB_PASSWORD: '666666',
        REDIS_HOST: 'localhost',
        REDIS_PORT: '6379',
      },
      error_file: '/var/log/codelens-api-error.log',
      out_file: '/var/log/codelens-api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '2560M',
    },
    {
      name: 'codelens-web',
      script: 'npx',
      args: 'serve -s dist -p 5173',
      cwd: '/root/CodeLens/apps/web',
      instances: 1,
      exec_mode: 'fork',
      env_production: {
        NODE_ENV: 'production',
      },
      error_file: '/var/log/codelens-web-error.log',
      out_file: '/var/log/codelens-web-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      autorestart: true,
    },
  ],
};
